<?php

/*
|--------------------------------------------------------------------------
| مفاتيح الدول (E.164)
|--------------------------------------------------------------------------
| الكويت أولاً ثم الدول العربية ثم بقية الدول أبجدياً بالإنجليزية.
| الدول التي تشترك في مفتاح واحد (مثل +1 و +44) تُرتَّب بحيث تأتي الدولة
| الرئيسية أولاً، لأن البحث عن المفتاح يعيد أول دولة مطابقة.
*/

return [
    ['iso' => 'KW', 'code' => '+965', 'ar' => 'الكويت', 'en' => 'Kuwait'],
    ['iso' => 'SA', 'code' => '+966', 'ar' => 'السعودية', 'en' => 'Saudi Arabia'],
    ['iso' => 'AE', 'code' => '+971', 'ar' => 'الإمارات', 'en' => 'United Arab Emirates'],
    ['iso' => 'QA', 'code' => '+974', 'ar' => 'قطر', 'en' => 'Qatar'],
    ['iso' => 'BH', 'code' => '+973', 'ar' => 'البحرين', 'en' => 'Bahrain'],
    ['iso' => 'OM', 'code' => '+968', 'ar' => 'عُمان', 'en' => 'Oman'],
    ['iso' => 'EG', 'code' => '+20', 'ar' => 'مصر', 'en' => 'Egypt'],
    ['iso' => 'JO', 'code' => '+962', 'ar' => 'الأردن', 'en' => 'Jordan'],
    ['iso' => 'IQ', 'code' => '+964', 'ar' => 'العراق', 'en' => 'Iraq'],
    ['iso' => 'LB', 'code' => '+961', 'ar' => 'لبنان', 'en' => 'Lebanon'],
    ['iso' => 'SY', 'code' => '+963', 'ar' => 'سوريا', 'en' => 'Syria'],
    ['iso' => 'PS', 'code' => '+970', 'ar' => 'فلسطين', 'en' => 'Palestine'],
    ['iso' => 'YE', 'code' => '+967', 'ar' => 'اليمن', 'en' => 'Yemen'],
    ['iso' => 'SD', 'code' => '+249', 'ar' => 'السودان', 'en' => 'Sudan'],
    ['iso' => 'LY', 'code' => '+218', 'ar' => 'ليبيا', 'en' => 'Libya'],
    ['iso' => 'TN', 'code' => '+216', 'ar' => 'تونس', 'en' => 'Tunisia'],
    ['iso' => 'DZ', 'code' => '+213', 'ar' => 'الجزائر', 'en' => 'Algeria'],
    ['iso' => 'MA', 'code' => '+212', 'ar' => 'المغرب', 'en' => 'Morocco'],
    ['iso' => 'MR', 'code' => '+222', 'ar' => 'موريتانيا', 'en' => 'Mauritania'],
    ['iso' => 'SO', 'code' => '+252', 'ar' => 'الصومال', 'en' => 'Somalia'],
    ['iso' => 'DJ', 'code' => '+253', 'ar' => 'جيبوتي', 'en' => 'Djibouti'],
    ['iso' => 'KM', 'code' => '+269', 'ar' => 'جزر القمر', 'en' => 'Comoros'],
    ['iso' => 'US', 'code' => '+1', 'ar' => 'الولايات المتحدة', 'en' => 'United States'],
    ['iso' => 'GB', 'code' => '+44', 'ar' => 'المملكة المتحدة', 'en' => 'United Kingdom'],
    ['iso' => 'IN', 'code' => '+91', 'ar' => 'الهند', 'en' => 'India'],
    ['iso' => 'PK', 'code' => '+92', 'ar' => 'باكستان', 'en' => 'Pakistan'],
    ['iso' => 'PH', 'code' => '+63', 'ar' => 'الفلبين', 'en' => 'Philippines'],
    ['iso' => 'BD', 'code' => '+880', 'ar' => 'بنغلاديش', 'en' => 'Bangladesh'],
    ['iso' => 'LK', 'code' => '+94', 'ar' => 'سريلانكا', 'en' => 'Sri Lanka'],
    ['iso' => 'NP', 'code' => '+977', 'ar' => 'نيبال', 'en' => 'Nepal'],
    ['iso' => 'ID', 'code' => '+62', 'ar' => 'إندونيسيا', 'en' => 'Indonesia'],
    ['iso' => 'IR', 'code' => '+98', 'ar' => 'إيران', 'en' => 'Iran'],
    ['iso' => 'TR', 'code' => '+90', 'ar' => 'تركيا', 'en' => 'Turkey'],
    ['iso' => 'AF', 'code' => '+93', 'ar' => 'أفغانستان', 'en' => 'Afghanistan'],
    ['iso' => 'AL', 'code' => '+355', 'ar' => 'ألبانيا', 'en' => 'Albania'],
    ['iso' => 'AS', 'code' => '+1684', 'ar' => 'ساموا الأمريكية', 'en' => 'American Samoa'],
    ['iso' => 'AD', 'code' => '+376', 'ar' => 'أندورا', 'en' => 'Andorra'],
    ['iso' => 'AO', 'code' => '+244', 'ar' => 'أنغولا', 'en' => 'Angola'],
    ['iso' => 'AI', 'code' => '+1264', 'ar' => 'أنغويلا', 'en' => 'Anguilla'],
    ['iso' => 'AG', 'code' => '+1268', 'ar' => 'أنتيغوا وباربودا', 'en' => 'Antigua and Barbuda'],
    ['iso' => 'AR', 'code' => '+54', 'ar' => 'الأرجنتين', 'en' => 'Argentina'],
    ['iso' => 'AM', 'code' => '+374', 'ar' => 'أرمينيا', 'en' => 'Armenia'],
    ['iso' => 'AW', 'code' => '+297', 'ar' => 'أروبا', 'en' => 'Aruba'],
    ['iso' => 'AU', 'code' => '+61', 'ar' => 'أستراليا', 'en' => 'Australia'],
    ['iso' => 'AT', 'code' => '+43', 'ar' => 'النمسا', 'en' => 'Austria'],
    ['iso' => 'AZ', 'code' => '+994', 'ar' => 'أذربيجان', 'en' => 'Azerbaijan'],
    ['iso' => 'BS', 'code' => '+1242', 'ar' => 'الباهاما', 'en' => 'Bahamas'],
    ['iso' => 'BB', 'code' => '+1246', 'ar' => 'باربادوس', 'en' => 'Barbados'],
    ['iso' => 'BY', 'code' => '+375', 'ar' => 'بيلاروسيا', 'en' => 'Belarus'],
    ['iso' => 'BE', 'code' => '+32', 'ar' => 'بلجيكا', 'en' => 'Belgium'],
    ['iso' => 'BZ', 'code' => '+501', 'ar' => 'بليز', 'en' => 'Belize'],
    ['iso' => 'BJ', 'code' => '+229', 'ar' => 'بنين', 'en' => 'Benin'],
    ['iso' => 'BM', 'code' => '+1441', 'ar' => 'برمودا', 'en' => 'Bermuda'],
    ['iso' => 'BT', 'code' => '+975', 'ar' => 'بوتان', 'en' => 'Bhutan'],
    ['iso' => 'BO', 'code' => '+591', 'ar' => 'بوليفيا', 'en' => 'Bolivia'],
    ['iso' => 'BA', 'code' => '+387', 'ar' => 'البوسنة والهرسك', 'en' => 'Bosnia and Herzegovina'],
    ['iso' => 'BW', 'code' => '+267', 'ar' => 'بوتسوانا', 'en' => 'Botswana'],
    ['iso' => 'BR', 'code' => '+55', 'ar' => 'البرازيل', 'en' => 'Brazil'],
    ['iso' => 'VG', 'code' => '+1284', 'ar' => 'جزر العذراء البريطانية', 'en' => 'British Virgin Islands'],
    ['iso' => 'BN', 'code' => '+673', 'ar' => 'بروناي', 'en' => 'Brunei'],
    ['iso' => 'BG', 'code' => '+359', 'ar' => 'بلغاريا', 'en' => 'Bulgaria'],
    ['iso' => 'BF', 'code' => '+226', 'ar' => 'بوركينا فاسو', 'en' => 'Burkina Faso'],
    ['iso' => 'BI', 'code' => '+257', 'ar' => 'بوروندي', 'en' => 'Burundi'],
    ['iso' => 'KH', 'code' => '+855', 'ar' => 'كمبوديا', 'en' => 'Cambodia'],
    ['iso' => 'CM', 'code' => '+237', 'ar' => 'الكاميرون', 'en' => 'Cameroon'],
    ['iso' => 'CA', 'code' => '+1', 'ar' => 'كندا', 'en' => 'Canada'],
    ['iso' => 'CV', 'code' => '+238', 'ar' => 'الرأس الأخضر', 'en' => 'Cape Verde'],
    ['iso' => 'KY', 'code' => '+1345', 'ar' => 'جزر كايمان', 'en' => 'Cayman Islands'],
    ['iso' => 'CF', 'code' => '+236', 'ar' => 'أفريقيا الوسطى', 'en' => 'Central African Republic'],
    ['iso' => 'TD', 'code' => '+235', 'ar' => 'تشاد', 'en' => 'Chad'],
    ['iso' => 'CL', 'code' => '+56', 'ar' => 'تشيلي', 'en' => 'Chile'],
    ['iso' => 'CN', 'code' => '+86', 'ar' => 'الصين', 'en' => 'China'],
    ['iso' => 'CO', 'code' => '+57', 'ar' => 'كولومبيا', 'en' => 'Colombia'],
    ['iso' => 'CG', 'code' => '+242', 'ar' => 'الكونغو', 'en' => 'Congo'],
    ['iso' => 'CD', 'code' => '+243', 'ar' => 'الكونغو الديمقراطية', 'en' => 'DR Congo'],
    ['iso' => 'CK', 'code' => '+682', 'ar' => 'جزر كوك', 'en' => 'Cook Islands'],
    ['iso' => 'CR', 'code' => '+506', 'ar' => 'كوستاريكا', 'en' => 'Costa Rica'],
    ['iso' => 'CI', 'code' => '+225', 'ar' => 'ساحل العاج', 'en' => "Cote d'Ivoire"],
    ['iso' => 'HR', 'code' => '+385', 'ar' => 'كرواتيا', 'en' => 'Croatia'],
    ['iso' => 'CU', 'code' => '+53', 'ar' => 'كوبا', 'en' => 'Cuba'],
    ['iso' => 'CW', 'code' => '+599', 'ar' => 'كوراساو', 'en' => 'Curacao'],
    ['iso' => 'CY', 'code' => '+357', 'ar' => 'قبرص', 'en' => 'Cyprus'],
    ['iso' => 'CZ', 'code' => '+420', 'ar' => 'التشيك', 'en' => 'Czech Republic'],
    ['iso' => 'DK', 'code' => '+45', 'ar' => 'الدنمارك', 'en' => 'Denmark'],
    ['iso' => 'DM', 'code' => '+1767', 'ar' => 'دومينيكا', 'en' => 'Dominica'],
    ['iso' => 'DO', 'code' => '+1809', 'ar' => 'الدومينيكان', 'en' => 'Dominican Republic'],
    ['iso' => 'EC', 'code' => '+593', 'ar' => 'الإكوادور', 'en' => 'Ecuador'],
    ['iso' => 'SV', 'code' => '+503', 'ar' => 'السلفادور', 'en' => 'El Salvador'],
    ['iso' => 'GQ', 'code' => '+240', 'ar' => 'غينيا الاستوائية', 'en' => 'Equatorial Guinea'],
    ['iso' => 'ER', 'code' => '+291', 'ar' => 'إريتريا', 'en' => 'Eritrea'],
    ['iso' => 'EE', 'code' => '+372', 'ar' => 'إستونيا', 'en' => 'Estonia'],
    ['iso' => 'SZ', 'code' => '+268', 'ar' => 'إسواتيني', 'en' => 'Eswatini'],
    ['iso' => 'ET', 'code' => '+251', 'ar' => 'إثيوبيا', 'en' => 'Ethiopia'],
    ['iso' => 'FK', 'code' => '+500', 'ar' => 'جزر فوكلاند', 'en' => 'Falkland Islands'],
    ['iso' => 'FO', 'code' => '+298', 'ar' => 'جزر فارو', 'en' => 'Faroe Islands'],
    ['iso' => 'FJ', 'code' => '+679', 'ar' => 'فيجي', 'en' => 'Fiji'],
    ['iso' => 'FI', 'code' => '+358', 'ar' => 'فنلندا', 'en' => 'Finland'],
    ['iso' => 'FR', 'code' => '+33', 'ar' => 'فرنسا', 'en' => 'France'],
    ['iso' => 'GF', 'code' => '+594', 'ar' => 'غويانا الفرنسية', 'en' => 'French Guiana'],
    ['iso' => 'PF', 'code' => '+689', 'ar' => 'بولينيزيا الفرنسية', 'en' => 'French Polynesia'],
    ['iso' => 'GA', 'code' => '+241', 'ar' => 'الغابون', 'en' => 'Gabon'],
    ['iso' => 'GM', 'code' => '+220', 'ar' => 'غامبيا', 'en' => 'Gambia'],
    ['iso' => 'GE', 'code' => '+995', 'ar' => 'جورجيا', 'en' => 'Georgia'],
    ['iso' => 'DE', 'code' => '+49', 'ar' => 'ألمانيا', 'en' => 'Germany'],
    ['iso' => 'GH', 'code' => '+233', 'ar' => 'غانا', 'en' => 'Ghana'],
    ['iso' => 'GI', 'code' => '+350', 'ar' => 'جبل طارق', 'en' => 'Gibraltar'],
    ['iso' => 'GR', 'code' => '+30', 'ar' => 'اليونان', 'en' => 'Greece'],
    ['iso' => 'GL', 'code' => '+299', 'ar' => 'غرينلاند', 'en' => 'Greenland'],
    ['iso' => 'GD', 'code' => '+1473', 'ar' => 'غرينادا', 'en' => 'Grenada'],
    ['iso' => 'GP', 'code' => '+590', 'ar' => 'غوادلوب', 'en' => 'Guadeloupe'],
    ['iso' => 'GU', 'code' => '+1671', 'ar' => 'غوام', 'en' => 'Guam'],
    ['iso' => 'GT', 'code' => '+502', 'ar' => 'غواتيمالا', 'en' => 'Guatemala'],
    ['iso' => 'GG', 'code' => '+44', 'ar' => 'غيرنزي', 'en' => 'Guernsey'],
    ['iso' => 'GN', 'code' => '+224', 'ar' => 'غينيا', 'en' => 'Guinea'],
    ['iso' => 'GW', 'code' => '+245', 'ar' => 'غينيا بيساو', 'en' => 'Guinea-Bissau'],
    ['iso' => 'GY', 'code' => '+592', 'ar' => 'غيانا', 'en' => 'Guyana'],
    ['iso' => 'HT', 'code' => '+509', 'ar' => 'هايتي', 'en' => 'Haiti'],
    ['iso' => 'HN', 'code' => '+504', 'ar' => 'هندوراس', 'en' => 'Honduras'],
    ['iso' => 'HK', 'code' => '+852', 'ar' => 'هونغ كونغ', 'en' => 'Hong Kong'],
    ['iso' => 'HU', 'code' => '+36', 'ar' => 'المجر', 'en' => 'Hungary'],
    ['iso' => 'IS', 'code' => '+354', 'ar' => 'آيسلندا', 'en' => 'Iceland'],
    ['iso' => 'IE', 'code' => '+353', 'ar' => 'أيرلندا', 'en' => 'Ireland'],
    ['iso' => 'IM', 'code' => '+44', 'ar' => 'جزيرة مان', 'en' => 'Isle of Man'],
    ['iso' => 'IT', 'code' => '+39', 'ar' => 'إيطاليا', 'en' => 'Italy'],
    ['iso' => 'JM', 'code' => '+1876', 'ar' => 'جامايكا', 'en' => 'Jamaica'],
    ['iso' => 'JP', 'code' => '+81', 'ar' => 'اليابان', 'en' => 'Japan'],
    ['iso' => 'JE', 'code' => '+44', 'ar' => 'جيرزي', 'en' => 'Jersey'],
    ['iso' => 'KZ', 'code' => '+7', 'ar' => 'كازاخستان', 'en' => 'Kazakhstan'],
    ['iso' => 'KE', 'code' => '+254', 'ar' => 'كينيا', 'en' => 'Kenya'],
    ['iso' => 'KI', 'code' => '+686', 'ar' => 'كيريباتي', 'en' => 'Kiribati'],
    ['iso' => 'XK', 'code' => '+383', 'ar' => 'كوسوفو', 'en' => 'Kosovo'],
    ['iso' => 'KG', 'code' => '+996', 'ar' => 'قيرغيزستان', 'en' => 'Kyrgyzstan'],
    ['iso' => 'LA', 'code' => '+856', 'ar' => 'لاوس', 'en' => 'Laos'],
    ['iso' => 'LV', 'code' => '+371', 'ar' => 'لاتفيا', 'en' => 'Latvia'],
    ['iso' => 'LS', 'code' => '+266', 'ar' => 'ليسوتو', 'en' => 'Lesotho'],
    ['iso' => 'LR', 'code' => '+231', 'ar' => 'ليبيريا', 'en' => 'Liberia'],
    ['iso' => 'LI', 'code' => '+423', 'ar' => 'ليختنشتاين', 'en' => 'Liechtenstein'],
    ['iso' => 'LT', 'code' => '+370', 'ar' => 'ليتوانيا', 'en' => 'Lithuania'],
    ['iso' => 'LU', 'code' => '+352', 'ar' => 'لوكسمبورغ', 'en' => 'Luxembourg'],
    ['iso' => 'MO', 'code' => '+853', 'ar' => 'ماكاو', 'en' => 'Macau'],
    ['iso' => 'MG', 'code' => '+261', 'ar' => 'مدغشقر', 'en' => 'Madagascar'],
    ['iso' => 'MW', 'code' => '+265', 'ar' => 'مالاوي', 'en' => 'Malawi'],
    ['iso' => 'MY', 'code' => '+60', 'ar' => 'ماليزيا', 'en' => 'Malaysia'],
    ['iso' => 'MV', 'code' => '+960', 'ar' => 'المالديف', 'en' => 'Maldives'],
    ['iso' => 'ML', 'code' => '+223', 'ar' => 'مالي', 'en' => 'Mali'],
    ['iso' => 'MT', 'code' => '+356', 'ar' => 'مالطا', 'en' => 'Malta'],
    ['iso' => 'MH', 'code' => '+692', 'ar' => 'جزر مارشال', 'en' => 'Marshall Islands'],
    ['iso' => 'MQ', 'code' => '+596', 'ar' => 'مارتينيك', 'en' => 'Martinique'],
    ['iso' => 'MU', 'code' => '+230', 'ar' => 'موريشيوس', 'en' => 'Mauritius'],
    ['iso' => 'YT', 'code' => '+262', 'ar' => 'مايوت', 'en' => 'Mayotte'],
    ['iso' => 'MX', 'code' => '+52', 'ar' => 'المكسيك', 'en' => 'Mexico'],
    ['iso' => 'FM', 'code' => '+691', 'ar' => 'ميكرونيزيا', 'en' => 'Micronesia'],
    ['iso' => 'MD', 'code' => '+373', 'ar' => 'مولدوفا', 'en' => 'Moldova'],
    ['iso' => 'MC', 'code' => '+377', 'ar' => 'موناكو', 'en' => 'Monaco'],
    ['iso' => 'MN', 'code' => '+976', 'ar' => 'منغوليا', 'en' => 'Mongolia'],
    ['iso' => 'ME', 'code' => '+382', 'ar' => 'الجبل الأسود', 'en' => 'Montenegro'],
    ['iso' => 'MS', 'code' => '+1664', 'ar' => 'مونتسرات', 'en' => 'Montserrat'],
    ['iso' => 'MZ', 'code' => '+258', 'ar' => 'موزمبيق', 'en' => 'Mozambique'],
    ['iso' => 'MM', 'code' => '+95', 'ar' => 'ميانمار', 'en' => 'Myanmar'],
    ['iso' => 'NA', 'code' => '+264', 'ar' => 'ناميبيا', 'en' => 'Namibia'],
    ['iso' => 'NR', 'code' => '+674', 'ar' => 'ناورو', 'en' => 'Nauru'],
    ['iso' => 'NL', 'code' => '+31', 'ar' => 'هولندا', 'en' => 'Netherlands'],
    ['iso' => 'NC', 'code' => '+687', 'ar' => 'كاليدونيا الجديدة', 'en' => 'New Caledonia'],
    ['iso' => 'NZ', 'code' => '+64', 'ar' => 'نيوزيلندا', 'en' => 'New Zealand'],
    ['iso' => 'NI', 'code' => '+505', 'ar' => 'نيكاراغوا', 'en' => 'Nicaragua'],
    ['iso' => 'NE', 'code' => '+227', 'ar' => 'النيجر', 'en' => 'Niger'],
    ['iso' => 'NG', 'code' => '+234', 'ar' => 'نيجيريا', 'en' => 'Nigeria'],
    ['iso' => 'NU', 'code' => '+683', 'ar' => 'نيوي', 'en' => 'Niue'],
    ['iso' => 'NF', 'code' => '+672', 'ar' => 'جزيرة نورفولك', 'en' => 'Norfolk Island'],
    ['iso' => 'KP', 'code' => '+850', 'ar' => 'كوريا الشمالية', 'en' => 'North Korea'],
    ['iso' => 'MK', 'code' => '+389', 'ar' => 'مقدونيا الشمالية', 'en' => 'North Macedonia'],
    ['iso' => 'MP', 'code' => '+1670', 'ar' => 'جزر ماريانا الشمالية', 'en' => 'Northern Mariana Islands'],
    ['iso' => 'NO', 'code' => '+47', 'ar' => 'النرويج', 'en' => 'Norway'],
    ['iso' => 'PW', 'code' => '+680', 'ar' => 'بالاو', 'en' => 'Palau'],
    ['iso' => 'PA', 'code' => '+507', 'ar' => 'بنما', 'en' => 'Panama'],
    ['iso' => 'PG', 'code' => '+675', 'ar' => 'بابوا غينيا الجديدة', 'en' => 'Papua New Guinea'],
    ['iso' => 'PY', 'code' => '+595', 'ar' => 'باراغواي', 'en' => 'Paraguay'],
    ['iso' => 'PE', 'code' => '+51', 'ar' => 'بيرو', 'en' => 'Peru'],
    ['iso' => 'PL', 'code' => '+48', 'ar' => 'بولندا', 'en' => 'Poland'],
    ['iso' => 'PT', 'code' => '+351', 'ar' => 'البرتغال', 'en' => 'Portugal'],
    ['iso' => 'PR', 'code' => '+1787', 'ar' => 'بورتوريكو', 'en' => 'Puerto Rico'],
    ['iso' => 'RE', 'code' => '+262', 'ar' => 'ريونيون', 'en' => 'Reunion'],
    ['iso' => 'RO', 'code' => '+40', 'ar' => 'رومانيا', 'en' => 'Romania'],
    ['iso' => 'RU', 'code' => '+7', 'ar' => 'روسيا', 'en' => 'Russia'],
    ['iso' => 'RW', 'code' => '+250', 'ar' => 'رواندا', 'en' => 'Rwanda'],
    ['iso' => 'BL', 'code' => '+590', 'ar' => 'سان بارتيليمي', 'en' => 'Saint Barthelemy'],
    ['iso' => 'SH', 'code' => '+290', 'ar' => 'سانت هيلينا', 'en' => 'Saint Helena'],
    ['iso' => 'KN', 'code' => '+1869', 'ar' => 'سانت كيتس ونيفيس', 'en' => 'Saint Kitts and Nevis'],
    ['iso' => 'LC', 'code' => '+1758', 'ar' => 'سانت لوسيا', 'en' => 'Saint Lucia'],
    ['iso' => 'MF', 'code' => '+590', 'ar' => 'سان مارتن', 'en' => 'Saint Martin'],
    ['iso' => 'PM', 'code' => '+508', 'ar' => 'سان بيير وميكلون', 'en' => 'Saint Pierre and Miquelon'],
    ['iso' => 'VC', 'code' => '+1784', 'ar' => 'سانت فينسنت والغرينادين', 'en' => 'Saint Vincent and the Grenadines'],
    ['iso' => 'WS', 'code' => '+685', 'ar' => 'ساموا', 'en' => 'Samoa'],
    ['iso' => 'SM', 'code' => '+378', 'ar' => 'سان مارينو', 'en' => 'San Marino'],
    ['iso' => 'ST', 'code' => '+239', 'ar' => 'ساو تومي وبرينسيب', 'en' => 'Sao Tome and Principe'],
    ['iso' => 'SN', 'code' => '+221', 'ar' => 'السنغال', 'en' => 'Senegal'],
    ['iso' => 'RS', 'code' => '+381', 'ar' => 'صربيا', 'en' => 'Serbia'],
    ['iso' => 'SC', 'code' => '+248', 'ar' => 'سيشل', 'en' => 'Seychelles'],
    ['iso' => 'SL', 'code' => '+232', 'ar' => 'سيراليون', 'en' => 'Sierra Leone'],
    ['iso' => 'SG', 'code' => '+65', 'ar' => 'سنغافورة', 'en' => 'Singapore'],
    ['iso' => 'SX', 'code' => '+1721', 'ar' => 'سينت مارتن', 'en' => 'Sint Maarten'],
    ['iso' => 'SK', 'code' => '+421', 'ar' => 'سلوفاكيا', 'en' => 'Slovakia'],
    ['iso' => 'SI', 'code' => '+386', 'ar' => 'سلوفينيا', 'en' => 'Slovenia'],
    ['iso' => 'SB', 'code' => '+677', 'ar' => 'جزر سليمان', 'en' => 'Solomon Islands'],
    ['iso' => 'ZA', 'code' => '+27', 'ar' => 'جنوب أفريقيا', 'en' => 'South Africa'],
    ['iso' => 'KR', 'code' => '+82', 'ar' => 'كوريا الجنوبية', 'en' => 'South Korea'],
    ['iso' => 'SS', 'code' => '+211', 'ar' => 'جنوب السودان', 'en' => 'South Sudan'],
    ['iso' => 'ES', 'code' => '+34', 'ar' => 'إسبانيا', 'en' => 'Spain'],
    ['iso' => 'SR', 'code' => '+597', 'ar' => 'سورينام', 'en' => 'Suriname'],
    ['iso' => 'SE', 'code' => '+46', 'ar' => 'السويد', 'en' => 'Sweden'],
    ['iso' => 'CH', 'code' => '+41', 'ar' => 'سويسرا', 'en' => 'Switzerland'],
    ['iso' => 'TW', 'code' => '+886', 'ar' => 'تايوان', 'en' => 'Taiwan'],
    ['iso' => 'TJ', 'code' => '+992', 'ar' => 'طاجيكستان', 'en' => 'Tajikistan'],
    ['iso' => 'TZ', 'code' => '+255', 'ar' => 'تنزانيا', 'en' => 'Tanzania'],
    ['iso' => 'TH', 'code' => '+66', 'ar' => 'تايلاند', 'en' => 'Thailand'],
    ['iso' => 'TL', 'code' => '+670', 'ar' => 'تيمور الشرقية', 'en' => 'Timor-Leste'],
    ['iso' => 'TG', 'code' => '+228', 'ar' => 'توغو', 'en' => 'Togo'],
    ['iso' => 'TK', 'code' => '+690', 'ar' => 'توكيلاو', 'en' => 'Tokelau'],
    ['iso' => 'TO', 'code' => '+676', 'ar' => 'تونغا', 'en' => 'Tonga'],
    ['iso' => 'TT', 'code' => '+1868', 'ar' => 'ترينيداد وتوباغو', 'en' => 'Trinidad and Tobago'],
    ['iso' => 'TM', 'code' => '+993', 'ar' => 'تركمانستان', 'en' => 'Turkmenistan'],
    ['iso' => 'TC', 'code' => '+1649', 'ar' => 'جزر توركس وكايكوس', 'en' => 'Turks and Caicos Islands'],
    ['iso' => 'TV', 'code' => '+688', 'ar' => 'توفالو', 'en' => 'Tuvalu'],
    ['iso' => 'UG', 'code' => '+256', 'ar' => 'أوغندا', 'en' => 'Uganda'],
    ['iso' => 'UA', 'code' => '+380', 'ar' => 'أوكرانيا', 'en' => 'Ukraine'],
    ['iso' => 'UY', 'code' => '+598', 'ar' => 'أوروغواي', 'en' => 'Uruguay'],
    ['iso' => 'VI', 'code' => '+1340', 'ar' => 'جزر العذراء الأمريكية', 'en' => 'US Virgin Islands'],
    ['iso' => 'UZ', 'code' => '+998', 'ar' => 'أوزبكستان', 'en' => 'Uzbekistan'],
    ['iso' => 'VU', 'code' => '+678', 'ar' => 'فانواتو', 'en' => 'Vanuatu'],
    ['iso' => 'VA', 'code' => '+39', 'ar' => 'الفاتيكان', 'en' => 'Vatican City'],
    ['iso' => 'VE', 'code' => '+58', 'ar' => 'فنزويلا', 'en' => 'Venezuela'],
    ['iso' => 'VN', 'code' => '+84', 'ar' => 'فيتنام', 'en' => 'Vietnam'],
    ['iso' => 'WF', 'code' => '+681', 'ar' => 'واليس وفوتونا', 'en' => 'Wallis and Futuna'],
    ['iso' => 'ZM', 'code' => '+260', 'ar' => 'زامبيا', 'en' => 'Zambia'],
    ['iso' => 'ZW', 'code' => '+263', 'ar' => 'زيمبابوي', 'en' => 'Zimbabwe'],
];
